#token.project1=sqa_fbe82c98ec69fe8a712d29edeffcd520c36ed500
#token.project2=sqa_fbe82c98ec69fe8a712d29edeffcd520c36ed500
token.project1=sqa_cdbcec19cca0e7c71ecdb2259f86acc42e329e27
token.project2=sqp_12dc2a74a7bd9f5c8080b0dafe2d611ad30f76a2
api1.address= http://localhost:9000
api2.address=http://localhost:5000
# Access Complexity Scores
score.access.high=9
score.access.medium=6
score.access.low=3
score.access.none=1

# Authentication Scores
score.auth.multiple=10
score.auth.single=7
score.auth.low=4
score.auth.none=1

# Severity Scores
score.severity.blocker=10
score.severity.critical=8
score.severity.major=5
score.severity.minor=2
score.severity.info=1


